config/routes.rb
Rails.application.routes.draw do
  root 'listings#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :listings
  resources :categories

end

app/models/admin.rb
class Admin < ActiveRecord::Base
    has_secure_password
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_and_belongs_to_many :listings
    
    def self.search(search)
      if search
        self.where("title like ?", "%#{search}%")
      else
        self.all
      end
    end
end

app/models/city.rb
class City < ActiveRecord::Base
    has_many :listings
end

app/models/listing.rb
class Listing < ActiveRecord::Base

    validates_presence_of :title, :link, :description, :deadline, :organization, :salary, :wage
    validates :salary, numericality: { greater_than_or_equal_to: 40000}, unless: "salary == 0"
    validate :deadline_greater_than_today
   
    has_and_belongs_to_many :categories
    belongs_to :city
    
    def deadline_greater_than_today
        if Date.today > self.deadline
            errors.add(:deadline, "Deadline must be greater than today's date")
        end
    end
    
    def self.search(search)
      if search
        self.where("title like ?", "%#{search}%")
      else
        self.all
      end
    end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper
  helper_method :order_type, :current_city
  def require_login
    unless logged_in?
      flash[:danger] = "You need to be logged in to do that!"
      redirect_to login_path
    else
      return true
    end
    
  end
  
  def order_type
    if params[:order_type].nil?
      return 'Posted Date'
    else
      return params[:order_type]
    end
  end
  
  def order_type_db

    return 'created_at DESC' if order_type == 'Posted Date'
    return order_type.downcase 
  end
  def current_city
    return params[:city] || 1
  end
  def city_listings type
    if params[:city].nil? or params[:city].empty?
      return type.all
    end
    type.where("city_id = ?", params[:city])
  end

  def listing_category type
    city_listings(type).search(params[:search]).order(order_type_db).paginate(:per_page => 8, :page => params[:page])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def new
       if require_login
          @category = Category.new 
       end
    end
    def create
        category = Category.new(category_params)
        if category.save
            flash[:success] = "You have created the #{category.title} category!"
            redirect_to new_listing_path
        else
           flash.now[:danger] = "Title must be present"
           render 'new'
        end
    end
    def show
        @category = Category.find_by(id: params[:id])
        @listings = listing_category(@category.listings)
        @categories = Category.all.order(:title)
    end
    
    private
    def category_params
        params.require(:category).permit(:title)
    end
    

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    before_action :require_login, :except => [:index, :show]
    
    def index
       @listings = listing_category(Listing)
       @categories = Category.all.order(:title)
    end
    def new
        
        @listing = Listing.new
        
    end
    
    def create
        @listing = Listing.new(listing_params)
        if @listing.save
            flash[:success] = "Created Listing"
            redirect_to new_listing_path
        else
            
            render 'new' 
        end
    end
    def destroy
        Listing.find(params[:id]).destroy  
        redirect_to root_path
    end
    def edit
       @listing = Listing.find(params[:id]) 
    end
    
    def update
        @listing = Listing.find(params[:id])
        
        if @listing.update_attributes(listing_params)
            flash[:success] = "You have edited the job posting, \"#{@listing.title}\""
            redirect_to root_path
        else
            render 'new' 
        end
    end
    
    
    private
    def listing_params
        params.require(:listing).permit(:title, :link,:description, :deadline, :salary, :wage,:organization,:city_id,:category_ids => [])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end
    
    def create
        user = Admin.find_by_username(params[:session][:username])
        if user && user.authenticate(params[:session][:password])
            log_in user
            redirect_to new_listing_path
        else
            flash.now[:danger] = "Incorrect password/username combination"
            render 'new'
        end
    end
    def destroy
       logout
       redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include SessionsHelper
    
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        Admin.find_by(id: session[:user_id]) 
    end
    def logged_in?
        !current_user.nil?
    end
    def log_in user
       session[:user_id] = user.id
    end
    def logout
       session.delete(:user_id) 
    end
end

app/views/categories/new.html.erb
<br/><br/>
<%= link_to "Create a new Job Post" %>
<%= form_for @category do |f| %>
    <table>
        <tr>
            <td><%= f.label :title %></td>
            <td><%= f.text_field :title %></td>
        </tr>
        <tr>
            <td><%= f.submit %></td>
        </tr>
    </table>
<% end %>

app/views/categories/show.html.erb
<br/>
<%= render 'shared/search_category'%>
<div class="top">
    <%= render 'shared/sort_category'%>
    <%= render 'shared/city_category' %>
    <h2><%= @category.title %></h2>
</div>
<%= render 'shared/listings' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gainxp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico'%>
</head>
<body>
<!-- Do sort by deadline -->
  <%= bootstrap_flash %>
  
  <div class="container">
    <div class="row">
    
      <div class="col-md-3" id="left">
        <%= link_to((image_tag '/assets/logo2.png', :id => "logo"), root_path) %>
        
        <% if !@categories.nil? %>
          <div class="filters">
            <h4>Filters</h4>
            <%= render 'shared/categories' %>        
          </div>
        <% end %>
      </div>
      
      
      <div class="col-md-6" id="center">
        <%= yield %>
      </div>
      
      <div class="col-md-3" id="right">
        <h4>About us</h4>
        <p>GainXP.ca <em>is a pure job listings website for <b>young professionals.</b></p>
        <p id="about_postings">The postings are <b>agency-free,</b> <br/>
        a minimum starting salary of <b>$40,000</b> <br/>
        and <b>less than 5 years required experience</b>
        </p>
        
        </em>
      </div>
    </div>
  </div>
  <!---
  <%= link_to "Home", root_path %>
  
  
  <% if logged_in? %>
  
    Hello, <%= current_user.username %>!
    <%= link_to "Create Listing", new_listing_path%>
    <%= link_to "Create Category", new_category_path%>
    <%= link_to "Logout", logout_path, :method => :delete %>
    
  <% else %>
    <%= link_to "Login", login_path %>
  <% end %>
  
  
  --->
</body>
</html>

app/views/listings/_errors.html.erb
<% if @listing.errors.any? %>
<ul>
  <% @listing.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

app/views/listings/edit.html.erb
<%= form_for(@listing) do |f| %>
  <%= render 'errors' %>
    <table>
        <tr>
            <td><%= f.label :title %></td>
            <td><%= f.text_field :title%></td>
        </tr>
        <tr>
            <td><%= f.label :link %></td>
            <td><%= f.text_field :link %></td>
        </tr>
        <tr>
            <td><%= f.label  "Yearly Salary" %></td>
            <td><%= f.number_field :salary %></td>
        </tr>
        <tr>
            <td><%= f.label "Hourly Wage (eg, $15)" %></td>
            <td><%= f.number_field :wage %></td>
        </tr>
        <tr>
            <td><%= f.label :organization%></td>
            <td><%= f.text_field :organization %></td>
        </tr>

        <tr>
            <td><%= f.label :deadline%></td>
            <td><%= f.date_select :deadline, order: [:day, :month, :year] %></td>
        </tr>
        <tr>
            <td><%= f.label :city%></td>
            <td><%= f.collection_select :city_id, City.all.order(:title), :id, :title, {}, {:multiple => false}%></td>
        </tr>
        <tr>
            <td><%= f.label :category %></td>
            <td><%= f.collection_select :category_ids, Category.all.order(:title), :id, :title, {}, {:multiple => true} %></td>
        </tr>
        <tr>
            <td><%= f.label :description %></td>
            <td><%= f.text_area :description, :size => "40x15"%></td>
        </tr>
        <tr>
            <td><%= f.submit "Update Posting" %></td>
        </tr>
    </table>
<% end %>

app/views/listings/index.html.erb
<br/>
<%= render 'shared/search'%>
<div class="top">
    <%= render 'shared/sort' %>
    <%= render 'shared/city' %>
    <h3 id="current_postings">Current Job Postings</h3>
    
</div>

<%= render 'shared/listings' %>

app/views/listings/new.html.erb
<br/><br/>
<%= link_to "Create a new Filter", new_category_path %>
<%= render 'errors' %>

<%= form_for Listing.new do |f| %>
        <table>
        <tr>
            <td><%= f.label :title %></td>
            <td><%= f.text_field :title%></td>
        </tr>
        <tr>
            <td><%= f.label :link %></td>
            <td><%= f.text_field :link %></td>
        </tr>
        <tr>
            <td><%= f.label  "Yearly Salary" %></td>
            <td><%= f.number_field :salary %></td>
        </tr>
        <tr>
            <td><%= f.label "Hourly Wage (eg, $15)" %></td>
            <td><%= f.number_field :wage %></td>
        </tr>
        <tr>
            <td><%= f.label :organization%></td>
            <td><%= f.text_field :organization %></td>
        </tr>

        <tr>
            <td><%= f.label :deadline%></td>
            <td><%= f.date_select :deadline, order: [:day, :month, :year] %></td>
        </tr>
        <tr>
            <td><%= f.label :city%></td>
            <td><%= f.collection_select :city_id, City.all.order(:title), :id, :title, {}, {:multiple => false}%></td>
        </tr>
        <tr>
            <td><%= f.label :category %></td>
            <td><%= f.collection_select :category_ids, Category.all.order(:title), :id, :title, {}, {:multiple => true} %></td>
        </tr>
        <tr>
            <td><%= f.label :description %></td>
            <td><%= f.text_area :description, :size => "40x15"%></td>
        </tr>
        <tr>
            <td><%= f.submit "Create Listing" %></td>
        </tr>
    </table>
<% end %>

app/views/shared/_categories.html.erb
<% @categories.each do |cat| %>
    <% if !@category.nil? and cat.title == @category.title %>
        <p class="current_category">
    <% else %>
        <p>
    <% end %>
    <%= link_to cat.title + "(#{cat.listings.count})", category_path(cat), :class => "category" %></p>
<% end %>

app/views/shared/_city.html.erb
<%= form_tag listings_path, :method => 'get', :class => "form-inline" do %>
  <%= render 'shared/inner_city' %>
<% end %>

app/views/shared/_city_category.html.erb
<%= form_tag category_path, :method => 'get' do %>
  <%= render 'shared/inner_city' %>
<% end %>

app/views/shared/_inner_city.html.erb
<span id="sort"><%= select_tag "city",  options_from_collection_for_select(City.all, 'id', 'title', current_city), :onchange => "this.form.submit();", :autocomplete => 'off' %></span>

app/views/shared/_inner_sort.html.erb
<span id="sort"><%= select_tag "order_type", options_for_select(['Deadline', 'Posted Date'], order_type), :onchange => "this.form.submit();", :autocomplete => 'off' %></span>

app/views/shared/_inside_search.html.erb
  <div class="input-group">
    <%= hidden_field_tag :city, params[:city] %>
    <%= hidden_field_tag :sort, params[:order_type]%>
    <%= text_field_tag :search, params[:search], :class => "form-control", :name => "search", :id => "search", :placeholder => "Search"%>
    
    <span class="input-group-btn">
      <%= button_tag(type: "submit", :class => "btn btn-default") do %>
        <small><span class="glyphicon glyphicon-search" id="sizing-addon2"></span></small>
      <% end %>
    </span>
  
  </div>

app/views/shared/_listings.html.erb
<% if !@listings.empty? %>

    <% @listings.each do |list| %>
        <div id="listing" class=<%= cycle('gray_listing', 'white_listing') %>>
            <span id="deadline">Deadline: <%= list.deadline.strftime('%b %d %Y') %></span>
            <h4><b><%= link_to list.title, list.link %></b></h4>
            
            <span id="organization"> <%= list.organization %>
                <% unless list.salary == 0 %>
                    <span id="salary">$<%= number_with_delimiter(list.salary, :demiliter => ',') %></span>
                <% else %>
                    <span id="salary">$<%= list.wage %>/hr</span>
                <% end %>
            </span>
            
            <p id="description"><%= list.description %></p>
            <p id="posted">Posted: <b><%= time_ago_in_words(list.created_at).titleize %> Ago</b></p>
            <p><%= list.city.title %></p>
                
           
            <% if logged_in? %>
                <div class="form-inline">
                <%= link_to "Edit", edit_listing_path(list), method: :get, :class => "btn btn-primary"%>
                <%= link_to "Destroy", list, data: {confirm: "Are you sure you want to delete this?"},method: :delete, :class => "btn btn-danger" %>
                
                </div>
            <% end %>
        </div>
    <% end %>
    <%= will_paginate @listings %>
<% elsif !params[:search].nil? && !@category.nil? %>
    <h5>No Job Postings Found in <%= @category.title %> with the keyword "<%= params[:search] %>"</h5>
<% elsif !params[:search].nil? %>
    <h5>No Job Postings Found With The Keyword(s) "<%= params[:search] %>"</h5>
<% elsif !params[:city].nil? %>
    <h5>No Job Postings Found in <%= City.find(params[:city]).title %></h5>
<% else %>
    <h5>No Job Postings Found in <%= @category.title %></h5>
<% end %>

app/views/shared/_search.html.erb
<%= form_tag listings_path, :method => 'get' do %>
  <%= render 'shared/inside_search' %>
<% end %>

app/views/shared/_search_category.html.erb
<%= form_tag category_path, :method => 'get' do %>
  <%= render 'shared/inside_search' %>
<% end %>

app/views/shared/_sort.html.erb
<%= form_tag listings_path, :method => 'get', :class => "form-inline" do %>
  <%= render 'shared/inner_sort' %>
<% end %>

app/views/shared/_sort_category.html.erb
<%= form_tag category_path, :method => 'get' do %>
  <%= render 'shared/inner_sort' %>
<% end %>